"""Генерирует пять полиномов Q2 под коэффициенты выбранного интегратора."""
from pathlib import Path
import re
import numpy as np
from numpy.polynomial import Chebyshev, Polynomial

ROOT = Path(__file__).resolve().parents[1]
DS = 1.9 * 25.8649e-3
DIS2 = 4e-9
INTERVALS = ((0., 4.), (4., 8.), (8., 12.), (12., 24.), (24., 54.))


def influence(method):
    suffix = {"euler": "", "bdf2": "_bdf2", "alpha02": "_alpha02"}[method]
    text = (ROOT / f"include/composed_frontend_fixture{suffix}.h").read_text(encoding="utf-8")
    return float(re.search(r"composed_b_influence\[1\]\[1\] = \{\s*\{([\d.eE+-]+)F", text)[1])


def exact(t, beta):
    t = np.asarray(t, dtype=np.float64)
    lo, hi = np.zeros_like(t), t.copy()
    for _ in range(64):
        mid = (lo + hi) * .5
        greater = mid + beta * np.sinh(mid) > t
        hi = np.where(greater, mid, hi)
        lo = np.where(greater, lo, mid)
    return (lo + hi) * .5


def coefficients(method):
    beta = influence(method) * DIS2 / DS
    result = []
    for low, high in INTERVALS:
        # Узлы Чебышёва, равномерная точность по всему интервалу.
        z = np.cos(np.pi * (np.arange(8192) + .5) / 8192)
        t = (low + high) * .5 + (high - low) * .5 * z
        fit = Chebyshev.fit(z, exact(t, beta), 5, domain=[-1, 1]).convert(kind=Polynomial)
        result.append(fit.coef)
    return result


def literal(value):
    text = format(float(np.float32(value)), ".9g")
    if "." not in text and "e" not in text:
        text += ".0"
    return text + "F"


def expression(coef):
    value = literal(coef[-1])
    for item in coef[-2::-1]:
        value = f"({value}*z+{literal(item)})"
    return value


def main():
    lines = ["/* Generated by simulation/generate_q2_polynomial.py; do not edit. */",
             "#ifndef COMPOSED_Q2_POLYNOMIAL_H", "#define COMPOSED_Q2_POLYNOMIAL_H"]
    for i, method in enumerate(("alpha02", "bdf2")):
        lines.append("#ifdef COMPOSED_GENERALIZED_ALPHA02" if i == 0 else "#else")
        lines.append(f"/* {method}: beta={influence(method)*DIS2/DS:.12g} */")
        for k, coef in enumerate(coefficients(method)):
            lines.append(f"#define Q2_POLY_{k}(z) {expression(coef)}")
    lines.extend(["#endif", "static float q2_analytic_predictor(float linear_q){",
                  " const float inv_ds=1.0F/DS;float t=__builtin_fabsf(linear_q)*inv_ds,z,y;"])
    normalizations = (".5F*t-1.0F", ".5F*t-3.0F", ".5F*t-5.0F",
                      "(t-18.0F)*(1.0F/6.0F)", "(t-39.0F)*(1.0F/15.0F)")
    for k, ((low, high), norm) in enumerate(zip(INTERVALS, normalizations)):
        branch = ("if" if k == 0 else "else if") + f"(t<{literal(high)})" if k < 4 else "else"
        lines.append(f" {branch}{{z={norm};y=Q2_POLY_{k}(z);}}")
    lines.extend([" return __builtin_copysignf(y*DS,linear_q);", "}"])
    lines.extend(f"#undef Q2_POLY_{k}" for k in range(5))
    lines.append("#endif")
    path = ROOT / "include/composed_q2_polynomial.h"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(path)


if __name__ == "__main__":
    main()
