/* Generated by simulation/generate_q2_polynomial.py; do not edit. */
#ifndef COMPOSED_Q2_POLYNOMIAL_H
#define COMPOSED_Q2_POLYNOMIAL_H
#ifdef COMPOSED_GENERALIZED_ALPHA02
/* alpha02: beta=0.00183350188663 */
#define Q2_POLY_0(z) (((((-0.00153268967F*z+-0.0044698501F)*z+-0.00870128255F)*z+-0.01275793F)*z+1.98638237F)*z+1.99338555F)
#define Q2_POLY_1(z) (((((0.00633108569F*z+0.0194978192F)*z+-0.0465885773F)*z+-0.264850676F)*z+1.56279671F)*z+5.72026682F)
#define Q2_POLY_2(z) (((((0.000112725087F*z+-0.00486302609F)*z+0.0296817403F)*z+-0.133699492F)*z+0.622723818F)*z+7.78840351F)
#define Q2_POLY_3(z) (((((0.010562391F*z+-0.0269261785F)*z+0.0564697385F)*z+-0.165237531F)*z+0.610697091F)*z+9.17241764F)
#define Q2_POLY_4(z) (((((0.00709583145F*z+-0.0178740006F)*z+0.0386256203F)*z+-0.122135997F)*z+0.506024897F)*z+10.3497467F)
#else
/* bdf2: beta=0.0020195422734 */
#define Q2_POLY_0(z) (((((-0.00162841124F*z+-0.00483202236F)*z+-0.00954492204F)*z+-0.0140301939F)*z+1.98502195F)*z+1.99272037F)
#define Q2_POLY_1(z) (((((0.00538628921F*z+0.0208227821F)*z+-0.0417444855F)*z+-0.271186978F)*z+1.53671098F)*z+5.69850779F)
#define Q2_POLY_2(z) (((((0.000203928677F*z+-0.00483751763F)*z+0.028652655F)*z+-0.129461721F)*z+0.610025764F)*z+7.72154236F)
#define Q2_POLY_3(z) (((((0.0101567646F*z+-0.0260478016F)*z+0.0551690236F)*z+-0.162573531F)*z+0.605341077F)*z+9.08557129F)
#define Q2_POLY_4(z) (((((0.00697764335F*z+-0.0176329557F)*z+0.0382862836F)*z+-0.121403478F)*z+0.504433632F)*z+10.2563601F)
#endif
static float q2_analytic_predictor(float linear_q){
 const float inv_ds=1.0F/DS;float t=__builtin_fabsf(linear_q)*inv_ds,z,y;
 if(t<4.0F){z=.5F*t-1.0F;y=Q2_POLY_0(z);}
 else if(t<8.0F){z=.5F*t-3.0F;y=Q2_POLY_1(z);}
 else if(t<12.0F){z=.5F*t-5.0F;y=Q2_POLY_2(z);}
 else if(t<24.0F){z=(t-18.0F)*(1.0F/6.0F);y=Q2_POLY_3(z);}
 else{z=(t-39.0F)*(1.0F/15.0F);y=Q2_POLY_4(z);}
 return __builtin_copysignf(y*DS,linear_q);
}
#undef Q2_POLY_0
#undef Q2_POLY_1
#undef Q2_POLY_2
#undef Q2_POLY_3
#undef Q2_POLY_4
#endif
